Add GTK handles
rust-windowing/raw-window-handle pull request #105
Opened 2022-12-20 21:42 UTC by notgull

This PR adds handles representing display and window handles for GTK 3 and 4.

2022-12-21 12:30 UTC, madsmtm approved these changes
Thanks, only a minor nit.

2022-12-21 12:30 UTC, madsmtm commented on src/unix.rs
> +/// Raw display handle for the GTK Tool Kit version 3.
Nit: Move these to a new file `src/gtk.rs`, since GTK supports non-unix platforms

2022-12-21 20:11 UTC, madsmtm commented on src/unix.rs
> +    pub display: *mut c_void,
In any case, shouldn't this actually be a [`GdkDisplay`](https://docs.gtk.org/gdk4/class.Display.html)?

2022-12-21 20:25 UTC, ids1024 commented on src/unix.rs
> +    pub display: *mut c_void,
Yeah, `GdkDisplay` is probably the closest thing to a "display handle" in GTK. It has subclasses like which in turn holds things like `wl_display`.

Normally the display is just global state you can get with `gdk_display_get_default()`. I don't know if GTK can ever work with a display that isn't the "default".

2022-12-22 18:15 UTC, notgull commented on src/unix.rs
> +    pub display: *mut c_void,
Since `GdkDisplay` is at the level below GTK, I wanted to avoid exposing it. I can add it anyways, if you want.

> Both GTK3 and GTK4 can be used without a GtkApplication. I guess NULL could be used in that case? What would the GtkApplication be needed for?

Yes, it can be null without any issues. `GtkApplication` can be used to tinker with the menu bar, which may actually be important in many cases.

2022-12-22 19:23 UTC, madsmtm commented on src/unix.rs
> +    pub display: *mut c_void,
That sounds somewhat reasonable, though I think we're using `RawDisplayHandle` wrongly for this, then? Like, ideally we should have `Raw{Application, Display, Window, Surface, ...}Handle`?

Anyhow, at the very least the variable should be renamed from `display` to `application`.

2022-12-22 19:56 UTC, ids1024 commented on src/unix.rs
> +    pub display: *mut c_void,
If the window is associated with an application, you can get it with `gtk_window_get_application()`. So it seems redundant, and possibly better to just leave the display handle empty like `WebDisplayHandle`.

2022-12-22 22:02 UTC, notgull commented on src/unix.rs
> +    pub display: *mut c_void,
I still think that we should have a pointer to it, if for no other reason than to elide a call to `gtk_window_get_application()`.

2022-12-24 12:51 UTC, kchibisov requested changes
Could you add a CHANGELOG entry for that as well.

2022-12-24 12:51 UTC, kchibisov commented on src/gtk.rs
> +    pub window: *mut c_void,
Maybe then it should be called `widget`?

2022-12-24 12:51 UTC, kchibisov commented on src/gtk.rs
> +    pub window: *mut c_void,
ditto.

2022-12-27 17:10 UTC, ids1024 commented
If this takes a "A pointer to a `GtkWidget`", how exactly would it be used? An arbitrary widget isn't necessarily something you can add a child widget to, etc.

2022-12-28 15:19 UTC, notgull commented
The more that I think about this, the more I think that we should discuss first how higher-level toolkits like GTK and Qt should integrate into this crate. I'll close this for now.

2022-12-28 15:19 UTC, closed without merging