Make raw_*_handle return a result
rust-windowing/raw-window-handle pull request #122
Opened 2023-06-09 02:54 UTC by notgull

This is a breaking change. Supersedes #104.

2023-06-09 03:13 UTC, Lokathor approved these changes

2023-06-09 03:13 UTC, Lokathor commented
This looks great, but I want others to have a chance to raise any concerns before we merge it.

2023-06-09 03:35 UTC, notgull commented
Sounds good! I'll loop in @ogoffart since this was originally their idea.

2023-06-09 05:45 UTC, madsmtm requested changes
My primary objection to this is still: How will this look for the user? Like, how are they expected to actually handle the error?

As I see it, most people will just end up doing an `unwrap`, since:
- They are correctly managing event lifecycles on Android, meaning that the handle will always be available.
- Or for Slint, the window they want to render into will be backed by a backend.

If any of those are not true, then that's a programmer error, and i.e. a _good_ use of panics, not something that needs to be recoverable.

2023-06-09 05:45 UTC, madsmtm commented on src/lib.rs
> +            Self::Unavailable => write!(f, "The underlying handle is not available"),
Error `Display` text should start with a lowercase letter

2023-06-09 05:45 UTC, madsmtm commented on src/borrowed.rs
> +    Raw(RawHandleError),
We're going to be removing this enum right? So that we only have the one error type?

In that case, I think the enum should just be called `Error`.

2023-06-09 05:45 UTC, madsmtm commented on src/lib.rs
> +    NotSupported,
What is the use-case for this?

The use-case discussed in https://github.com/rust-windowing/raw-window-handle/pull/104 would use `Unavailable`, since that's what most accurately describes their situation?

2023-06-09 13:23 UTC, madsmtm commented
> So this crate should be trying to limit its major version increase.

Agreed. Or alternatively use the semver trick to avoid the issues.

2023-06-09 14:15 UTC, notgull commented
If the choice is between "return an error" or "not returning an error", I would say we should return an error. On the Android winit backend, there is a case where the function panics if the window is currently suspended. I would rather return an error than panic in this case.

2023-06-09 14:26 UTC, kchibisov commented on src/lib.rs
> +    NotSupported,
When the library can't provide a any handle for the current platform, but still somehow built for it. Or when multiple could be provided at the same time, like XLIB and XCB, but it was compiled without xlib, so it'll be not-available in generic cfg less code.

2023-06-09 14:27 UTC, kchibisov commented
We could have similar issue as Android with Wayland layer shell windows, so it's a good idea in general.

Ack from me.

2023-06-09 14:54 UTC, notgull commented on src/lib.rs
> +            Self::Unavailable => write!(f, "The underlying handle is not available"),
Is there a precedent for this? I've always started my error messages with a capital letter.

2023-06-09 19:25 UTC, madsmtm commented
> n the Android winit backend, there is a case where the function panics if the window is currently suspended. I would rather return an error than panic in this case.

I understand; I'm trying to figure out how the user is expected to handle that error?

2023-06-09 19:38 UTC, Lokathor commented
Any handling more graceful than a panic is a good idea, honestly.

2023-06-09 23:45 UTC, notgull commented on src/lib.rs
> +    NotSupported,
The idea is that:

- `NotSupported` is when the underlying windowing system does not support returning any of the C window handles. For instance, if you're using a pure Rust implementation of X11 or Wayland, or if you're using something that `raw-window-handle` doesn't support (like a game console).
- `Unavailable` is when the window is temporarily not available. The use case here is Android after a suspend event. There are probably others.

Handling these two error conditions may require separate code for certain cases.

2023-06-10 00:51 UTC, notgull commented
> But What is concerns me is the fact that it is a breaking change that this will require a semver version increase which will fragment the ecosystem.
> 
> The whole point of this crate is that it can be used to glue other crates together, and it is exposed in the public api of other crates. So this crate should be trying to limit its major version increase.

The tree of robust architecture must be refreshed from time to time with the blood of breaking changes. Making the `HasRawWindowHandle` trait have an infallible function was reasonable at the time that the trait was created but has become unreasonable in the modern day. The current model already results in panics that can be avoided through the use of Rust's error handling system. Keeping the model as it is right now *will* result in code that *assumes* that `raw_window_handle` is infallible; code that is *incorrect*.

To address the comments above, except for obvious cases that are blatantly programmer bugs (like using the wrong ordering in `compare_exchange` or using zero-sized chunks in `array_chunks`), it is never correct to design an API where panicking is an expected operation. By definition, panics are not expected to be recovered from. If an API user wants to panic if the window handle is inaccessible, they can do that with this API. The added complexity is minimal; only an `unwrap()` or an `if let Ok(..)` in the vast majority of cases will be necessary. At worst, the program will never become *less* robust that it currently is.

We already have a breaking change that needs to be made (the removal of `Active`). There are other breaking changes that may be on the table as well. For instance, with the introduction of borrowed window handles, does `HasRawWindowHandle` still need to be unsafe?

2023-06-10 06:05 UTC, madsmtm commented
> obvious cases that are blatantly programmer bugs

What I'm not convinced of is that this isn't such a case? If the application has been suspended, you shouldn't even _try_ to do any rendering, i.e. trying to access the window handle in that case _is_ a "blatant programmer bug". It is not something the application can recover from, it is something that must change in the code.

Am I missing something here? Is there a feasible way to recover? If someone can give me a `wgpu`, `glutin` or `softbuffer` + `winit` example where the error was properly handled (and not just unwrapped), my concerns would be sated.

2023-06-10 13:19 UTC, kchibisov requested changes
It's not clear to me whether this is a breaking change or not.

I think the CHANGELOG is sort of desynced, given that we have `0.5.2` on crates.io and the file is at `0.5.1`.

2023-06-10 13:28 UTC, Lokathor commented
That's probably my fault on the changelog. I'm not sure I'll have time to look into it myself today, but I'll definitely have to fix it before the next release, yeah.

2023-06-10 14:07 UTC, notgull commented
> It's not clear to me whether this is a breaking change or not.

This is a breaking change since it modifies the return value of a method of a trait in a backwards-incompatible way.

> I think the CHANGELOG is sort of desynced, given that we have `0.5.2` on crates.io and the file is at `0.5.1`.

Fixed in #124

2023-06-10 14:29 UTC, kchibisov commented
>This is a breaking change since it modifies the return value of a method of a trait in a backwards-incompatible way.

Then it should be stated in the changelog.

2023-06-10 16:26 UTC, notgull commented
> What I'm not convinced of is that this isn't such a case? If the application has been suspended, you shouldn't even _try_ to do any rendering, i.e. trying to access the window handle in that case _is_ a "blatant programmer bug". It is not something the application can recover from, it is something that must change in the code.
> 
> Am I missing something here? Is there a feasible way to recover? If someone can give me a `wgpu`, `glutin` or `softbuffer` + `winit` example where the error was properly handled (and not just unwrapped), my concerns would be sated.

Let's say I create a windowing framework that may use either a pure Rust implementation of X11 or the `libxcb` implementation. Let's also say that I have a rendering library built on top of this windowing framework. I want this renderer to use a hardware implementation like `wgpu` if it can, but fall back to software rendering if it can't. In that case I would have code like this:

```rust
if let Ok(handle) = my_window.window_handle() {
    use_wgpu_to_render_to_this_handle(handle);
} else {
    use_software_rasterization();
}
```

Granted, a similar affect *could* be achieved with feature flags, but this is more idiomatic because it doesn't rely on out-of-band compiler mechanisms.

For the `Unavailable` use case, it's good to be fault-tolerant of mistakes, especially ones that can come up during lifecycle handling. I would argue that even experienced programmers can and will make mistakes over what is valid during what parts of the GUI lifecycle. At the very least, something like this should be possible:

```rust
if let Ok(handle) = my_window.window_handle() {
    // Do rendering here.
}

// If we can't access the window handle, just do nothing. It's better than panicking
// here, especially in production.
```

> Then it should be stated in the changelog.

Fixed!

2023-06-10 17:35 UTC, madsmtm reviewed
Thanks for the examples @notgull!

I still feel like the argument is kinda weak, if the issue is that people make mistakes regarding lifetime management, then we should work on making that easier to avoid, not adding a hack to this library.

But I realize that I'm in the minority, and probably arguing about something fundamentally inconsequential, so I'll withdraw my objections.

2023-06-11 14:14 UTC, notgull commented
@rib or @MarijnS95, if you have a moment could you provide your thoughts regarding Android. The `Unavailable` error case exists mostly to make Android support a little easier.

2023-06-11 15:18 UTC, rib commented
NB there is also a potential wayland use case here too. The wayland winit backed currently jumps through significant hoops to make it look like there is no async configure where it can't return a valid handle beforehand. It leads to the whole backend buffering wayland events which shouldn't be necessary.

2023-06-11 16:41 UTC, kchibisov commented
>The wayland winit backed currently jumps through significant hoops to make it look like there is no async configure where it can't return a valid handle beforehand. It leads to the whole backend buffering wayland events which shouldn't be necessary.

That's not correct, the buffering is due to winit not using `&mut` and me refusing do the `unsafe` transmute, because it's not maintainable for no reason, you get events in the batches anyway.

The Wayland use case I've mentioned above, and layer shell behaves exactly like Android, where surface destroys when you power off or dpms the output. So it's required for it as well.

2023-06-12 07:19 UTC, rib commented
> > The wayland winit backed currently jumps through significant hoops to make it look like there is no async configure where it can't return a valid handle beforehand. It leads to the whole backend buffering wayland events which shouldn't be necessary.
> 
> That's not correct, the buffering is due to winit not using `&mut` and me refusing do the `unsafe` transmute, because it's not maintainable for no reason, you get events in the batches anyway.

I might be misremembering some details but, from what I recall they are related. The backend wouldn't be needing to use `&mut` if it wasn't trying to insert a synchronous roundtrip to the compositor within `Window::new()`, which it's doing to ensure the surface is configured.

If the backend could expose the fact that you can't query a raw handle until the configure comes back (asynchronously) from the compositor then it seems like it would be possible to remove any need for a round trip outside of the main event loop and so there would be no need to buffer events in the wayland backend.

2023-06-12 07:21 UTC, rib commented
> @rib or @MarijnS95, if you have a moment could you provide your thoughts regarding Android. The `Unavailable` error case exists mostly to make Android support a little easier.

This change looks good to me, thanks!

2023-06-12 07:21 UTC, rib approved these changes

2023-06-12 07:26 UTC, kchibisov commented
>If the backend could expose the fact that you can't query a raw handle until the configure comes back (asynchronously) from the compositor then it seems like it would be possible to remove any need for a round trip outside of the main event loop and so there would be no need to buffer events in the wayland backend.

I think what we could do is to make a window return just `WindowId`(we know it ahead of time) and the real window will be send to you later on or immediately if it's possible.

2023-06-15 15:18 UTC, notgull commented
Alright, it's been a week. Does anyone else have any comments before this is merged?

I've already reached out to the `wgpu` people and they seem fine with it.

cc @rust-windowing/winit, @rust-windowing/glutin, since you're the primary consumers of the `HasRawWindowHandle` trait

2023-06-15 16:45 UTC, kchibisov approved these changes

2023-06-15 18:14 UTC, Lokathor commented
Using `Error` with no prefix (eg: `HandleError`) is definitely not great. The official naming guidelines are just wrong, and that's not how the standard library works. io::Error and fmt::Error are the *outliers*, everything else is a ParseIntError or a Utf8Error or some other fully named error type. I think we should use a fully named enum here too.

Other than that, which you could consider non-blocking I guess, then I approve the PR.

2023-06-16 09:56 UTC, madsmtm commented on src/lib.rs
> +            Self::Unavailable => write!(f, "The underlying handle is not available"),
Well the [`Error`](https://doc.rust-lang.org/stable/std/error/trait.Error.html) trait itself recommends it

2023-06-16 10:00 UTC, madsmtm commented on src/lib.rs
> +    NotSupported,
Would be cool to have some of those example uses in the docs

2023-06-17 03:33 UTC, merged

2023-06-17 04:24 UTC, ogoffart commented
Is there going to be a "server trick" to avoid breaking the ecosystem?

2023-06-17 10:53 UTC, madsmtm commented
I'll try to if possible, see https://github.com/rust-windowing/raw-window-handle/issues/125