Add wasm-bindgen v0.2 handles for web_sys::HtmlCanvasElement and web_sys::OffscreenCanvas
rust-windowing/raw-window-handle pull request #134
Opened 2023-07-17 01:17 UTC by notgull

Closes #102 by adding two new window handles. One represents a `web_sys::HtmlCanvasElement` registered into `wasm-bindgen` through its index and the other represents a `web_sys::OffscreenCanvas` in the same way. This allows the handles to contain arbitrary canvases without needing to rely on the `id` hack.

The main issue with this PR is that the underlying representation for `wasm-bindgen` objects might change to something aside from the current index system. This was raised in https://github.com/rustwasm/wasm-bindgen/issues/1766. However, the index system has remained in place for five years and according to @daxpedda it isn't going anywhere soon. In addition a new system would likely require a breaking change. Therefore we should be fine with this system for the foreseeable future.

2023-07-17 01:27 UTC, grovesNL commented
Could we expose the regular web-sys types (`HtmlCanvasElement` and `OffscreenCanvas`) instead? `FromWasmAbi` and `IntoWasmAbi` transfer ownership of the JavaScript object, so it's really easy to get this wrong and drop the window, ending up with a use-after-free by accident.

2023-07-17 01:29 UTC, notgull commented
> Could we expose the regular web-sys types (`HtmlCanvasElement` and `OffscreenCanvas`) instead? `FromWasmAbi` and `IntoWasmAbi` transfer ownership of the JavaScript object, so it's really easy to get this wrong and drop the window, ending up with a use-after-free by accident.

This would require importing the `web-sys` crate, which is bad for a couple of reasons.

- It requires us to have `cfg` guards on the window handle itself, which is something I'm trying to avoid (#63)
- `web-sys` is a very heavy dependency for a crate that's supposed to be lean and mean.

2023-07-17 01:42 UTC, grovesNL commented
For what it's worth wgpu tried to use `WasmAbi` functions for a similar use case and ended up having to back them out because of the ownership issues (https://github.com/gfx-rs/wgpu/issues/3430 has some more context if you're interested).

> It requires us to have `cfg` guards on the window handle itself

Could we avoid this by making the web-sys handles type aliases or opaque types that use `()` on other targets?

> `web-sys` is a very heavy dependency for a crate that's supposed to be lean and mean.

Agreed but `web-sys` will most likely be in use already for people using this target, and we could still use cfg/feature guards if anyone would like to opt-out.

2023-07-17 02:19 UTC, notgull commented
> For what it's worth wgpu tried to use `WasmAbi` functions for a similar use case and ended up having to back them out because of the ownership issues ([gfx-rs/wgpu#3430](https://github.com/gfx-rs/wgpu/issues/3430) has some more context if you're interested).

We could likely solve this on our end by making the `FromWasmAbi` results `ManuallyDrop`. This is how it's done in other places where raw pointers are used like this, like in `Waker`s.

> Could we avoid this by making the web-sys handles type aliases or opaque types that use `()` on other targets?

This adds a layer of `cfg` complexity I'm uncomfortable having.

2023-07-17 02:59 UTC, grovesNL commented
At least anecdotally based on my experience removing the use of `WasmAbi` in wgpu, I wouldn't feel confident accepting these handles and converting them back into `web_sys` types. For example, if one raw window handle is reused to create two `HtmlCanvasElement` from the `u32` representation then this would break in a subtle way.

2023-07-17 03:15 UTC, notgull commented
> At least anecdotally based on my experience removing the use of `WasmAbi` in wgpu, I wouldn't feel confident accepting these handles and converting them back into `web_sys` types. For example, if one raw window handle is reused to create two `HtmlCanvasElement` from the `u32` representation then this would break in a subtle way.

Unless there's a subtlety I'm missing it seems like just wrapping the result of `FromWasmAbi` in `ManuallyDrop` should be enough to prevent this double-drop from occurring.

2023-07-17 04:13 UTC, grovesNL commented
My understanding is that it goes something like this because of the ownership transfer that happens when you go through `IntoWasmAbi`/`FromWasmAbi`:
- the owner of `HtmlCanvasElement` (e.g., winit) calls `into_abi` and gets a value like `10u32` and puts it into a raw window handle
- then the raw window handle is handed to another crate (e.g., wgpu) and `10u32` is converted back to `HtmlCanvasElement` (optionally wrapped with `ManuallyDrop`) and it's used for some initial setup code, eventually dropped
- then the raw window handle is used again (e.g., same crate as before or another) but `10u32` isn't actually valid to be used for the next `from_abi` call

2023-07-17 05:22 UTC, notgull commented
> - then the raw window handle is handed to another crate (e.g., wgpu) and `10u32` is converted back to `HtmlCanvasElement` (optionally wrapped with `ManuallyDrop`) and it's used for some initial setup code, **eventually dropped**

Emphasis mine. As long as the canvas element is never dropped by the other crate there isn't a double drop. It can be either forgotten or wrapped in `ManuallyDrop` as I did above. As long as the original window source is kept alive you can be sure that the canvas reference is valid, and this can now be done thanks to borrowed window handles.

2023-07-17 11:23 UTC, grovesNL commented
In my example, wgpu wouldn't need the handle anymore so wgpu would drop it, but I thought this would invalidate the ABI handle for future reuse (e.g. passing it to wgpu or another crate). Is my understanding wrong?

2023-07-17 12:07 UTC, daxpedda commented
> In my example, wgpu wouldn't need the handle anymore so wgpu would drop it, but I thought this would invalidate the ABI handle for future reuse (e.g. passing it to wgpu or another crate).

I didn't follow the exact discussion so far, but if you drop the `JsValue`, any "pointers" to it will become invalid indeed. A trait implementer could avoid this by cloning the `JsValue` internally and return the "pointer" to that.

2023-07-18 02:48 UTC, notgull commented
To sum up what was discussed in the Matrix room: the idea is that ownership isn't really passed through the `idx` value to `wgpu`/`glutin`/`softbuffer`/etc. The `winit::Window` or whatever is what really owns the `Canvas`; when the `Window` is dropped the `Canvas` is dropped.

The renderer, then, only owns a "reference" to that `Canvas`. It would call `FromWasmAbi` to get a `Canvas`, place that in a `ManuallyDrop`, and then *never drop it*. Semantically it's similar to a borrow. Once the renderer is dropped, the `Canvas` isn't dropped with it; it's just left for the windowing system to drop it.

In chat this was compared to `Arc::from_ptr()` and `Arc::into_ptr()`. This strategy is actually used somewhat frequently in cases where pointers are being passed around. See [this code](https://github.com/smol-rs/waker-fn/blob/6b47138087c81d53590a290e54e9092a9c195a03/src/lib.rs#L55-L58) from `smol` for an example.

@daxpedda Does this implementation look right? As you're the resident expert on `wasm-bindgen` I'll defer to you on this before I merge it.

2023-07-18 07:08 UTC, daxpedda commented
As far as I understood the explained implementation, it is correct. It would all be unsafe though until you somehow introduce a lifetime that binds it to the owner of `Canvas`.

2023-07-18 15:25 UTC, notgull commented
Yes, as @daxpedda said the "thing can be double dropped if you aren't careful" problem would not be unique to these handles. Pretty much every resource contained in these window handles have resources associated with them that can't be dropped twice. It's up the the windowing system to own it and the rendering system to not drop it.

2023-07-18 15:33 UTC, grovesNL commented
> I don't know much about RWH, but my impression so far was that this is the same issue other backends have as well.

That's true, although temporary canvases are a common pattern for wasm projects (in contrast to native windows which are typically long-lived), especially projects that aren't  using a windowing system like winit. Those projects won't be able to use raw-window-handle using this approach without leaking. This would work well if we used web-sys types instead.

2023-07-18 23:49 UTC, notgull commented
> That's true, although temporary canvases are a common pattern for wasm projects (in contrast to native windows which are typically long-lived), especially projects that aren't  using a windowing system like winit. Those projects won't be able to use raw-window-handle using this approach without leaking. 

Using the new borrowed handle system it should be possible to parameterize rendering types by the object managing the canvas. This should make it easy from a user perspective to write a wrapper around temporary canvases to work in this manner.

> This would work well if we used web-sys types instead.

One of the main sticking points for `raw-window-handle` is its lack of `cfg` guards and dependencies. I find the current solution, as hacky as it may be, preferable to going back on both of these points.

2023-07-30 16:29 UTC, notgull commented
Given that there have been no comments on this thread for a while, and that the Web maintainer for `winit` has signed off on this, it seems to me that there are no more open issues and that this can be merged.

I'll give it a week before I do just in case anyone else has any comments.

2023-07-31 00:46 UTC, grovesNL commented
> Using the new borrowed handle system it should be possible to parameterize rendering types by the object managing the canvas. This should make it easy from a user perspective to write a wrapper around temporary canvases to work in this manner.

In this case you'd want the rendering types to have a strong reference to the temporary canvas in this case, so the rendering types would effectively have to become the owner.

> One of the main sticking points for `raw-window-handle` is its lack of `cfg` guards and dependencies. I find the current solution, as hacky as it may be, preferable to going back on both of these points.

1. I think a `cfg` guard to alias web types internally is different than the concerns raised in #63 The point is that you have to be on the wasm target in order to use web-sys types anyway, so these are already guarded at some level (either at the crate level or wasm-specific paths in on both sides of handle creation/usage). In other words, downstream crates already have to guard these paths, so it shouldn't affect the ergonomics negatively as raised in #63

2. It's not possible to create or use these handles without web-sys already being somewhere in the dependency tree on this target, so while it's a nice goal to have as few dependencies as possible, it doesn't add dependencies if you actually want to use the handle. Almost any crate targeting the web/wasm will already have web-sys as a dependency.

I appreciate trying to be consistent in exposing these handles, and we can proceed with this if people believe it's the best path forward. I'd just like to reiterate that using these ABI handles is:
- unsafe and error-prone because it relies on the under-documented ABI conversion features of wasm-bindgen which in turn makes the ownership story unclear and easy to accidentally cause a use-after-free or leak canvases
- problematic trying to support common web use cases with a temporary canvas being handed off to the renderer

It would also be unfortunate to add this complexity back into wgpu after recently removing it because of the ownership/borrowing/refcounting challenges the ABI functions caused.

The alternative of wrapping web-sys types is what downstream crates would naturally expect, and these types are what people already pass today (if they're not going through raw-window-handle). I feel like the most pragmatic solution is to wrap the web-sys types and having a target-gated dependency, even though it's not consistent with how other handles are exposed<sup>1</sup>.

<sup>1</sup> Although I'd argue other handles would also try to use something better than `*mut c_void` if platforms/libraries could've historically agreed on a handle type that was stronger than that, like the handles web-sys provides in this case.

2023-07-31 01:05 UTC, madsmtm commented
I'll propose another solution: Expose the `JsValue` only through `cfg`-gated methods, and enable the methods based on a feature flag (instead of a specific platform).

Something like the following (showing an extension to the hypothetical future of a `web-sys v0.4`).
```toml
# Cargo.toml
[dependencies]
web-sys-0-3 = { package = "web-sys", version = "0.3" }
web-sys-0-4 = { package = "web-sys", version = "0.4" }
```

```rust
pub struct Wbg02CanvasWindowHandle(Inner);

// Private
enum Inner {
    #[cfg(feature = "web-sys-0-3")]
    V0_3(web_sys_0_3::JsValue),
    #[cfg(feature = "web-sys-0-4")]
    V0_4(web_sys_0_4::JsValue),
}

impl Wbg02CanvasWindowHandle {
    #[cfg(feature = "web-sys-0-3")]
    pub fn new_0_3(js_value: web_sys_0_3::JsValue) -> Self {
        Self(Inner::V0_3(js_value))
    }

    #[cfg(feature = "web-sys-0-4")]
    pub fn new_0_4(js_value: web_sys_0_4::JsValue) -> Self {
        Self(Inner::V0_4(js_value))
    }

    #[cfg(feature = "web-sys-0-3")]
    pub fn value_0_3(&self) -> Option<js_value: web_sys_0_3::JsValue> {
        match self.inner {
            Inner::V0_3(value) => Some(value),
            _ => None
        }
    }

    #[cfg(feature = "web-sys-0-4")]
    pub fn value_0_4(&self) -> Option<js_value: web_sys_0_4::JsValue> {
        match self.inner {
            Inner::V0_4(value) => Some(value),
            _ => None
        }
    }
}
```

2023-08-04 00:38 UTC, notgull commented
If we were to go this direction, I would prefer to use `JsValue` instead of `web-sys` types directly in order to avoid potential version churn.

I've just realized that the additional downside of including types like that would be that it would make it impossible to release `raw-window-handle` version 1.0, and therefore other 1.0 releases of other crates (like, say, `glutin`). Unless `wasm-bindgen` is planning on bumping from v0.2 to v1.0 anytime soon it would essentially trap the entire Rust GUI ecosystem into an unstable version.

I'll still re-iterate my past points, as even with the proposed model it still becomes increasingly more complicated to construct handles with little added benefit (as the downstream consumer is expected to be using `unsafe` anyways, I would hope that they closely read the documentation).

2023-08-04 00:50 UTC, Lokathor commented
Getting this to 1.0 is absolutely a goal. However, we don't need to get the whole crate to 1.0 all at once. Even within rust itself it's common for some parts to stabilize before others (eg: inline asm).

We *could* gate the entire browser handle system behind optional dependencies/features and document it as still experimental even while the rest of the crate for desktop/mobile is moved up to 1.0. If necessary the feature can be called something more generic like `browser` if we want to avoid favoring a particular crate.

2023-08-04 02:31 UTC, notgull commented
I would like to avoid using a feature in this case. If we hit 1.0, then `wasm-bindgen` or whatever hits 1.0, we'll have a hanging feature that does nothing that we can't get rid of. In this case I would prefer a `cfg` directive, like `--cfg rwh_semver_exempt_web_handles`.

2023-08-04 02:32 UTC, grovesNL commented
> Unless `wasm-bindgen` is planning on bumping from v0.2 to v1.0 anytime soon it would essentially trap the entire Rust GUI ecosystem into an unstable version.

For what it's worth, this is already the case in most crates that supporting this target, e.g. [winit](https://github.com/rust-windowing/winit/blob/189a0080a6df9169b549c405e73328d74e83fcbb/src/platform/web.rs#L50), [wgpu](https://github.com/gfx-rs/wgpu/blob/052bd17d41c227628ba2a6b9c56d8f8af299fb8f/wgpu/src/backend/web.rs#L618), [glow](https://github.com/grovesNL/glow/blob/3c06c30ff370452397f49f840013d86a339b3709/src/web_sys.rs#L1152), [egui's eframe](https://github.com/emilk/egui/blob/bdc8795b0476c25faab927fc3c731f2d79f2098f/crates/eframe/src/web/mod.rs#L99), [leptos](https://github.com/leptos-rs/leptos/blob/4001561987f97752195b673beca19b9373629a22/leptos_dom/src/helpers.rs#L9), etc. all expose `web_sys` types in their public API for the same reasons I've tried to outline - it's much more convenient to work with these typed handles than requiring them to go through the wasm ABI or similar, and the dependency will already be in-tree for this target.

2023-08-04 02:41 UTC, Lokathor commented
I don't think a special cfg instead of a cargo feature is very user friendly. Users expect to be able to look at the features list and have it really be the list without secret extra options.

As to having a feature that eventually does nothing: It's really not a big deal. If we really wanted we could even remove the feature (since we're not promising the feature is part of our stable API in the first place) if it was really so offense to the sensibilities, but it's the best user experience to just let an opt-in feature "do nothing" once it's eventually part of the default setup.

2023-08-04 04:40 UTC, notgull commented
Yeah, now that you put it that way. I'll rewrite this PR to use `wasm-bindgen` then, if everyone else is fine with it.

2023-08-05 00:36 UTC, notgull commented
Ah wait, `JsValue` is not `Copy`. That kind of throws a wrench in the entire thing, as we need `RawWindowHandle` to be `Copy`.

So, I think the current implementation of this PR is still the best way of doing it.

2023-08-05 01:14 UTC, grovesNL commented
Ah that's too bad. Opened #138 to see if it's worthwhile to consider lifting that.

2023-09-02 04:16 UTC, notgull commented
I've now replaced the wasm-bindgen handles such that they use actual wasm-bindgen objects. This also solves the `Copy` issue mentioned in #142

2023-09-02 04:47 UTC, notgull commented
cc @grovesNL

2023-09-02 10:57 UTC, madsmtm requested changes

2023-09-02 10:57 UTC, madsmtm commented on Cargo.toml
> +unstable_web_handles = ["wasm-bindgen", "std"]
You're already naming the types for `wasm-bindgen` `v0.2`; I think the feature name should include the version as well?

2023-09-02 10:57 UTC, madsmtm commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
So, I tried to read the above discussion, but I still don't understand why we don't store the value in a way that it can be `Copy`?

Taking my purist hat on for a second, this would be really nice because then `WindowHandle<'a>` really _would_ be a borrowed handle.

<details>
<summary>I can think of at least three ways to solve that</summary>

### Just use a pointer

Just use a pointer to `JsValue`. E.g. we'd store `NonNull<JsValue>`, and let the implementer ensure that the pointer is valid for the lifetime of the implementer.

### Transmute the bytes

Unsafely using something like `val: [u8; mem::size_of::<JsValue>()]`.
On initialization we'd take a `&JsValue` and copy the bytes, and to pass back a reference we'd cast a pointer to the bytes to a `*const JsValue`, and then convert that to a reference.

Though of course this assumes a few things about `JsValue`, like that it doesn't have interior mutability, but still less than if we store a `u32`.

### Don't have raw handle on WASM

We could have platform-specific raw and borrowed handles, e.g. `AppkitWindowHandle<'a> { raw: RawAppkitWindowHandle, p: PhantomData<&'a ()> }`. This would allow the web backend to expose `WasmWindowHandle<'a>(&'a JsValue)`, but not the raw one, if people don't like pointers.
</details>

I agree that even nicer would be to have something that owns the window handles, and `Drop`s them when necessary - if we took a page out of `std::os::fd`'s book, something like an `OwnedWindowHandle` that itself implements `HasWindowHandle`. This would be useful on _all_ platforms!

But the problem with that is, again, dependencies, which is something that `raw-window-handle` tries hard to avoid.

2023-09-02 13:45 UTC, grovesNL commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
Could you clarify the benefits of making it `Copy` internally? What’s the use case for reusing a window handle multiple times where cloning wouldn’t be reasonable?

> let the implementer ensure that the pointer is valid for the lifetime of the implementer

As described above, this would break common use cases where people temporarily get a JsValue for a canvas somewhere then drop it after handing it off to the graphics API. They could work around this by leaking the JsValue then using a pointer. This would be a significant  downgrade from how people already manage this today, so I don't expect people to go through raw window handle if that's the case.

> Transmute the bytes

Conceptually JsValue is Arc-like, so it has all the same downsides of pretending Arc is Copy and the same problems as the WasmAbi functions as described above. e.g., you’re effectively creating as many weak references as you want but not tracking this anywhere.

2023-09-02 14:08 UTC, notgull commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
One of the main sticking points above is that making the WASM handle `Copy` leads to footguns, so I'd rather avoid this if possible.

2023-09-02 14:11 UTC, madsmtm commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
I think having `Copy` is more from a purist perspective, not _that_ important.

But the great value of the pointer solution is that once we have a pointer `NonNull<JsValue>`, we can just do `NonNull<c_void>`, and then avoid the dependency altogether (ofc we'd still have to version it in the type, but we need not have the actual dependency, which is great for compile times and such).

> As described above, this would break common use cases where people temporarily get a JsValue for a canvas somewhere then drop it after handing it off to the graphics API. They could work around this by leaking the JsValue then using a pointer. This would be a significant downgrade from how people already manage this today, so I don't expect people to go through raw window handle if that's the case.

I'm not that familiar with WASM, but it seems like rendering libraries would have to retain the `JsValue` themselves if they are to use it past the lifetime of the `WindowHandle<'a>` they've been given, right?

E.g. let's assume a rendering library function `fn render(&self, handle: WindowHandle<'a>) -> ...` that renders into a provided canvas. They have basically three options:
- Render right away.
- Store the `WindowHandle<'a>`, in which case they either have to carry the lifetime `'a` along, preventing the parent `JsValue` used to construct the window handle from being dropped until they do.
- Clone the `JsValue`, and manage the lifetime themselves.

In all cases a pointer to `JsValue` (or to `HtmlCanvasElement`, or whatever) seem perfectly fine to me? Or am I missing something?

2023-09-02 14:15 UTC, madsmtm commented
Another argument for keeping `raw-window-handle` completely dependency-free: It can more easily be integrated into other projects, e.g. maybe `web-sys` should be the one depending on `raw-window-handle`?

Just a thought, I've at least thought about adding support for it in `icrate`, but have held off because `raw-window-handle` doesn't _guarantee_ it won't have any dependencies (which is very important for low-level libraries to avoid a cyclic dependency in the future).

2023-09-02 14:17 UTC, daxpedda commented
> [..] maybe `web-sys` should be the one depending on `raw-window-handle`?

It is unlikely to happen, `web-sys` is supposed to be bindings only, even Serde support was removed/deprecated. It's a `*-sys` crate after all.

2023-09-02 14:54 UTC, grovesNL commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
> (ofc we'd still have to version it in the type, but we need not have the actual dependency, which is great for compile times and such).

The dependency will almost always (I'd guess >99% of the time) already be in-tree on either or both sides (producer and consumer of the handle) for this target, so I'm not sure about the trade-off of avoiding a dependency that's likely to be in-tree by removing type safety and adding pointer casts.

> In all cases a pointer to JsValue (or to HtmlCanvasElement, or whatever) seem perfectly fine to me? Or am I missing something?

That could work as long as the consumer is able to dereference and clone the `JsValue`, it's just extra pointer casts for producers and consumers to get wrong.

2023-09-02 15:24 UTC, notgull commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
> But the great value of the pointer solution is that once we have a pointer `NonNull<JsValue>`, we can just do `NonNull<c_void>`, and then avoid the dependency altogether (ofc we'd still have to version it in the type, but we need not have the actual dependency, which is great for compile times and such).

I'm against having opaque pointers to Rust types. It's possible for two versions of `wasm-bindgen` to be compiled into an executable, and unless the type is explicitly defined like it is here it's impossible to tell which version it's pointing to.

2023-09-02 15:26 UTC, notgull commented
> Just a thought, I've at least thought about adding support for it in `icrate`, but have held off because `raw-window-handle` doesn't _guarantee_ it won't have any dependencies (which is very important for low-level libraries to avoid a cyclic dependency in the future).

The dependency is only present in web targets; I am committed to maintaining `raw-window-handle`'s dependency-free status for desktop and mobile platforms. So it should still be fine to add to `icrate`.

2023-09-02 15:37 UTC, Lokathor commented
> It's a *-sys crate after all.

Even a sys crate usually declares types, and thus can implement appropriate traits on those types. Not that it has to depend on us and do that, but it would be reasonable

2023-09-02 15:49 UTC, daxpedda commented
> Even a sys crate usually declares types, and thus can implement appropriate traits on those types. Not that it has to depend on us and do that, but it would be reasonable

Wasn't a question of "can", but of "should". My impression so far is that `*-sys` crates tend to have as few dependencies as possible and let others depend on them instead of the other way around.

This isn't a rule somewhere, so I don't think it's totally unreasonable.
Would anybody be interested to make a PR (when we get there) to `web-sys` so that I can review it and discuss it with the others in Rustwasm? Myself I'm not familiar at all with `raw-window-handle`.

2023-09-02 15:50 UTC, daxpedda commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
You can't have two versions of `wasm-bindgen` compiled into the same executable, other then the fact that it wouldn't work anyway, the CLI tool prevents it.

2023-09-02 15:58 UTC, madsmtm commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
> The dependency will almost always (I'd guess >99% of the time) already be in-tree on either or both sides (producer and consumer of the handle) for this target, so I'm not sure about the trade-off of avoiding a dependency that's likely to be in-tree by removing type safety and adding pointer casts.

> it's just extra pointer casts for producers and consumers to get wrong.

Very true! Indeed it _is_ a trade-off between "ease of use"/"safety" and "no dependencies"/"consistency". That trade-off was made with the other platforms, where the problem of dependencies are arguably worse, and where the ABI story is better.

My opinion is still that the better choice is "no dependencies", partly because of consistency, partly for the other reasons described, but I can see why we disagree.

> and unless the type is explicitly defined like it is here it's impossible to tell which version it's pointing to.

Hmm, I don't see how `Wbg02CanvasWindowHandle(NonNull<c_void>)` or something like that could possibly refer to multiple versions of `wasm-bindgen`? Though I get that people could accidentally forget to update the name when they update the dependency, and there'd be no safeguards against that.

2023-09-02 16:45 UTC, notgull commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
> My opinion is still that the better choice is "no dependencies", partly because of consistency, partly for the other reasons described, but I can see why we disagree.

As much as the idea of having zero dependencies appeals to me, I'm leaning towards the current option. If only because the footguns introduced otherwise would be a deal breaker for `wgpu` (I assume that @grovesNL is speaking for them).

> Hmm, I don't see how `Wbg02CanvasWindowHandle(NonNull<c_void>)` or something like that could possibly refer to multiple versions of `wasm-bindgen`? Though I get that people could accidentally forget to update the name when they update the dependency, and there'd be no safeguards against that.

Turns out that it can't (thanks Daxpedda), but it would be an issue for other pure Rust handles.

2023-09-02 17:24 UTC, madsmtm commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
Okay, how about this then:
```rust
pub enum RawWindowHandle {
    WebOffscreenCanvas(WebOffscreenCanvasWindowHandle),
    WebCanvas(WebCanvasWindowHandle),
    // ...
}

pub struct WebOffscreenCanvasWindowHandle {
    /// The `JsValue` of an `OffscreenCanvas`.
    pub value: NonNull<c_void>,
}

#[cfg(feature = "wasm-bindgen-0-2")]
impl WebOffscreenCanvasWindowHandle {
    pub fn from_0_2(canvas: &wasm_bindgen::JsValue) -> Self {
        Self { value: NonNull::from(canvas).cast::<c_void>() }
    }

    // Safe if the handle is gotten through `WindowHandle<'a>`, which ensures validity of the pointers and such
    pub unsafe fn get_0_2(&self) -> &wasm_bindgen::JsValue {
        unsafe { self.value.cast::<wasm_bindgen::JsValue>().as_ref() }
    }
}

// Or for even more type-safety
#[cfg(feature = "web-sys-0-3")]
impl WebOffscreenCanvasWindowHandle {
    pub fn from_web_sys_0_3(canvas: &web_sys::OffscreenCanvas) -> Self {
        let value: &wasm_bindgen::JsValue = &canvas; // Deref
        Self::from_0_2(value)
    }

    // Safe if the handle is gotten through `WindowHandle<'a>`, which ensures validity of the pointers and such.
    pub unsafe fn get_web_sys_0_3(&self) -> &web_sys::OffscreenCanvas {
        OffscreenCanvas::unchecked_from_js_ref(self.get_0_2())
    }
}

// `HtmlCanvasElement`
pub struct WebCanvasWindowHandle { pub value: NonNull<c_void> }

// Similar impls for `WebCanvasWindowHandle`
```

Since `wasm-bindgen` is already ensured to be unique, there's no need for the versioning scheme on the name.

This would give us `Copy` back, we wouldn't have variants that directly depend on `cfg`s, and it would allow `raw-window-handle` to more easily handle upgrades to the dependency (and would allow windowing libraries and graphics libraries to do the casts themselves, leading to faster compile-times by unblocking `raw-window-handle` in the compilation graph, since it can avoid depending on `web-sys` directly).

2023-09-02 17:59 UTC, notgull commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
That sounds fine to me. @grovesNL Does this work for `wgpu`?

2023-09-02 18:40 UTC, grovesNL commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
That would work ok for wgpu and I definitely don't want to block progress here.

I personally think this is the wrong tradeoff (e.g. very real risk of use-after-free as we've seen with people trying ash for the first time) and we shouldn't be forcing people to deal with pointer casting type safe handles to c_void just to always recover the same type on the other side, especially because it's a downgrade from what people are already doing (passing type safe handles directly to graphics APIs). The original goal of raw-window-handle was to make interop easier between crates, but this makes it harder to get right.

2023-09-02 19:31 UTC, notgull commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
Agreeing with the above, in addition to the fact that casting Rust types to and from a C void pointer feels very unclean to me.

2023-09-02 20:37 UTC, madsmtm commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
I think we should go for this design then for now - I am definitely open for discussing further, though we should probably do so in a separate issue (esp. after we've seen how the design of `WindowHandle<'_>` actually works out in practice).

@notgull do you want to take a stab at it in this PR?

2023-09-02 21:04 UTC, notgull commented on src/web.rs
> +    idx: wasm_bindgen::JsValue,
I've changed it to this for now. I'll open an issue once this PR is merged about this.

2023-09-02 22:08 UTC, madsmtm requested changes
Nice, thanks @notgull!

2023-09-02 22:08 UTC, madsmtm commented on Cargo.toml
> +# The point being: rely on this at your own peril.
I know that I've been vocal about it, but honestly, if we have the dependency anyhow, we might as well make it stable, no? I mean, `raw-window-handle` is not yet stable, so we can always deprecate an remove it later if we feel the need to.

2023-09-02 22:08 UTC, madsmtm commented on src/web.rs
> +    /// Create a new handle to an [`HtmlCanvasElement`].
Nit: Make it clear that we're dealing with a pointer

```suggestion
    /// Create a new handle to a pointer to a [`HtmlCanvasElement`].
```

2023-09-02 22:08 UTC, madsmtm commented on src/web.rs
> +    /// of [`HtmlCanvasElement`]. The pointer is a direct reference to a [`JsValue`].
Nit: wording ("it is implied" sounds odd).

```suggestion
    /// A pointer to the [`JsValue`] of a [`HtmlCanvasElement`].
    ///
    /// The object must be registered in the [`wasm-bindgen`] table.
```

(Unsure what you meant my "registered", so I kept it)

2023-09-02 22:08 UTC, madsmtm commented on src/web.rs
> +pub struct Wbg02CanvasWindowHandle {
Name doesn't have to include version info, since there can only be one instance of `wasm-bindgen` (though we should definitely document that assumption)

2023-09-02 22:08 UTC, madsmtm commented on src/web.rs
> +    pub unsafe fn from_wasm_bindgen_0_2(js_value: &wasm_bindgen::JsValue) -> Self {
This function doesn't need to be `unsafe`, the safety guarantees are upheld in `WindowHandle::new`

2023-09-02 22:08 UTC, madsmtm commented on src/web.rs
> +        doc(cfg(all(target_family = "wasm", feature = "unstable_web_handles_wbg_02")))
Nit: I suspect placing this on the `impl` instead would have the same effect in the docs?

2023-09-02 22:25 UTC, notgull commented on Cargo.toml
> +features = ["std"]
`wasm-bindgen` fails to compile without it.

2023-09-02 22:34 UTC, notgull commented on Cargo.toml
> +# The point being: rely on this at your own peril.
If we make it not unstable, then if we upgrade to version 1.0 we can't do the semver trick in 0.6 so backport these changes.

2023-09-02 22:36 UTC, notgull commented on src/web.rs
> +pub struct Wbg02CanvasWindowHandle {
If `wasm-bindgen` 1.0 is released, then it would be a breaking change to change it. So for semver reasons it should be versioned.

2023-09-02 22:40 UTC, madsmtm commented on Cargo.toml
> +features = ["std"]
Ah, fair enough. Why do we need to enable `"std"` for ourselves then?

2023-09-02 22:44 UTC, madsmtm commented on Cargo.toml
> +# The point being: rely on this at your own peril.
Well, nowadays we can't do the semver trick anyhow...

But anyhow, maybe that's just how it'll have to be? Like, then we release `v1.0` of `raw-window-handle`, and just forever expose a (likely deprecated when future `wasm-bindgen` versions come out) way to access `wasm-bindgen` `v0.2` traits. Annoying, sure, but better than the code of users of this feature (of which there will be many) failing to compile suddenly after a `cargo update`, no?

2023-09-02 22:45 UTC, notgull commented on Cargo.toml
> +features = ["std"]
I think it's so `wasm-bindgen` can disable `std` in the future once they stop depending on it.

2023-09-02 22:48 UTC, madsmtm commented on src/web.rs
> +pub struct Wbg02CanvasWindowHandle {
I don't think it would, since if there can only be one version of `wasm-bindgen` in a given binary.

Like, the `NonNull<c_void>` just points to a `wasm_bindgen::JsValue`, whether that is currently `v0.2`, `v0.3` or `v1.0` is irrelevant - it's ensured to always be the same between the windowing and graphics crate you're using, right?

2023-09-02 22:54 UTC, notgull commented on src/web.rs
> +pub struct Wbg02CanvasWindowHandle {
Yeah that makes sense, do you mind making the change? I'm at a football game right now (friends think I am scrolling Twitter) so I won't have laptop access for a few hours

2023-09-02 22:55 UTC, notgull commented on Cargo.toml
> +# The point being: rely on this at your own peril.
I see your point. Then, just make it a stable feature.

2023-09-02 22:59 UTC, madsmtm commented on src/borrowed.rs
> -#[derive(PartialEq, Eq, Hash, Copy, Clone)]
Rather do the opposite; re-add `Copy` to `WindowHandle<'_>`, now that we can again.

2023-09-02 22:59 UTC, madsmtm commented on src/web.rs
> +    /// ```
Nit: No fields to set later, make it actually explain a little bit about what to do, and let CI run it.

```suggestion
    /// # Example
    ///
    /// ```
    /// # use core::ffi::c_void;
    /// # use core::ptr::NonNull;
    /// # use raw_window_handle::Wbg02CanvasWindowHandle;
    /// # type HtmlCanvasElement = ();
    /// # type JsValue = ();
    /// let canvas: &HtmlCanvasElement;
    /// # canvas = &();
    /// let value: &JsValue = &canvas; // Deref to `JsValue`
    /// let obj: NonNull<c_void> = NonNull::from(value).cast();
    /// let mut handle = Wbg02CanvasWindowHandle::new(obj);
    /// ```
```

2023-09-02 22:59 UTC, madsmtm commented on src/web.rs
> +    /// # Safety
Nit: Not a safety comment, though still keep the comment

2023-09-02 23:00 UTC, madsmtm commented on src/web.rs
> +pub struct Wbg02CanvasWindowHandle {
Gladly!

2023-09-02 23:00 UTC, madsmtm commented on Cargo.toml
> +features = ["std"]
I meant, why are we enabling `raw-window-handle`'s own `"std"` feature when the `wasm-bindgen` feature is enabled?

2023-09-02 23:32 UTC, madsmtm commented on src/web.rs
> +    /// let value: &JsValue = &canvas; // Deref to `JsValue`
@daxpedda: Is the ABI of `OffscreenCanvas` and `JsValue` guaranteed to be the same? E.g. is it sound to transmute `&OffscreenCanvas -> &JsValue`?

2023-09-02 23:39 UTC, madsmtm commented on src/web.rs
> +    /// [`HtmlCanvasElement`]: https://docs.rs/web-sys/latest/web_sys/struct.HtmlCanvasElement.html
@daxpedda: Do you have a reference for this? How guaranteed is it that there will never be two `wasm-bindgen`?

2023-09-02 23:42 UTC, madsmtm commented on src/web.rs
> +    // the binary will simply fail to compile!
@daxpedda: Do you have a reference for this? How guaranteed is it that there will never be two `wasm-bindgen`?

2023-09-02 23:53 UTC, daxpedda commented on src/web.rs
> +    /// let value: &JsValue = &canvas; // Deref to `JsValue`
Looking at this code, the `OffscreenCanvas` is first dereferenced to `JsValue`, that is then converted to a pointer. If you convert that pointer back to a `JsValue`, that works. I wouldn't convert the `JsValue` pointer to a `OffscreenCanvas` value, same rules as Rust applies here.

Unless `OffscreenCanvas` is a `#[repr(transparent)]` wrapper around `JsValue`, it won't work. Which currently it does, but it doesn't say anywhere that this is stable stuff a user can rely on. I honestly have no clue if Rust API guidelines says that this stuff should be stable in libraries or not.

2023-09-03 00:02 UTC, daxpedda commented on src/web.rs
> +    // the binary will simply fail to compile!
It is not 100% guaranteed.

But generally speaking the way `wasm-bindgen` works prevents this, because it encodes "stuff" into the Wasm binary that needs to be interpreted by the CLI tool, so multiple versions will always be incompatible unless `wasm-bindgen` becomes a completely different beast.

That said, it was discussed in the past to move `wasm-bindgen` to the component model (which isn't stable yet) and drop the CLI completely at some point. This would probably allow multiple versions of `wasm-bindgen` to co-exist in the same binary, but old versions will still be unusable. But considering that `wasm-bindgen` is not actively developed anymore and there are now things like `wit-bindgen`, I doubt this will ever happen.

```rust
    // the binary will simply fail to compile!
```

I believe it should compile, but you won't be able to use it. Without the CLI tool it won't work on any runtime and the CLI tool will fail if you have multiple versions.

2023-09-03 02:03 UTC, madsmtm commented on src/web.rs
> +    /// let value: &JsValue = &canvas; // Deref to `JsValue`
Yeah, I kinda figured the `#[repr(transparent)]` wasn't a stable promise (though the attribute may show up in `rustdoc`, it's not a stable promise unless the docs say it is).

2023-09-03 03:34 UTC, notgull commented on Cargo.toml
> +features = ["std"]
Huh, I remember it not compiling, but apparently it does? Odd.

2023-09-03 03:34 UTC, notgull reviewed
+1 to all of your changes @madsmtm

I'd be fine with merging now and bikeshedding later

2023-09-03 06:26 UTC, daxpedda commented on src/web.rs
> +    /// let value: &JsValue = &canvas; // Deref to `JsValue`
FWIW: it shows up in the [documentation](https://docs.rs/web-sys/0.3.64/web_sys/struct.OffscreenCanvas.html).

2023-09-03 15:40 UTC, merged