Add connector_id to DrmWindowHandle
rust-windowing/raw-window-handle pull request #170
Opened 2024-07-05 19:23 UTC by morr0ne

This pull request introduces a new field to the DRM display handle to specify the connector id.

Rationale:
Without a connector, the file descriptor may point to a DRM device that lacks any connected displays, rendering it non-functional and arguably not a valid handle. By adding the connector_id field, we ensure that the display handle accurately represents a connected and usable display.

2024-07-05 19:30 UTC, Lokathor commented
Changing the signature of `new` is a breaking change, which we wouldn't want to do here. Adding the public field to a non-exhaustive struct is fine though.

Can we just add the field, as well as a doc comment if necessary, but not change any method signatures?

2024-07-05 19:34 UTC, kchibisov commented
I don't think that connector should go there, because connector is display and I don't think any one stops you from drawing into device without connectors attached and e.g. copy to other GPU which has connectors attached?

Also, if multiples are present, which connector should be used?

2024-07-05 19:48 UTC, morr0ne commented
> I don't think that connector should go there, because connector is display and I don't think any one stops you from drawing into device without connectors attached and e.g. copy to other GPU which has connectors attached?

That's exactly why it should go here. If you want to draw to a display the only way is to get a connector otherwise you have no way to create something to draw too. If you want to copy to another gpu then you should use the Handle of that gpu. Without the connector there is no handle to a display because there is no display.

> Also, if multiples are present, which connector should be used?

That is up to the provider of the handle to decide.

To ensure we handle cases where programs rely on the device without a connector then we could specify the connect_id as an Option. This would also fix the problem mentioned above since we could just pass `None` when calling new thus making this a non breaking change.

2024-07-05 19:51 UTC, morr0ne commented
I also realized that instead of a u32 I should have used a NonZeroU32. Going with the above would also mean we get a nicely aligned layout since the size of `Option<NonZeroU32>` is guaranteed to be the same as `u32`

2024-07-05 19:58 UTC, kchibisov commented
But you can have lots of connectors per once device so it doesn't make much sense, and `Display` handle is not for _drawing_ it's for getting a some kind of _device_. Your connector is also hotplug, while device is not.

connector is also not required to create any drawing setups with OpenGL/Vulkan, etc, because you draw into `Window`.

So if anywhere connector could be an optional field on `DrmWindowHandle`, but then drm APIs accept array of connectors IIRC.

2024-07-05 20:06 UTC, morr0ne commented
It appears I misunderstood the difference between the display and the window handle. Given this clarification, I agree that placing the connector in the window handle is more logical.

To provide additional context, this change is necessary for adding support to wgpu. Specifically, Vulkan requires a connector_id when creating the surface. You can see how this is used here: https://github.com/gfx-rs/wgpu/pull/5908

2024-07-05 20:21 UTC, kchibisov commented on src/unix.rs
> +    pub connector_id: Option<NonZeroU32>,
Should document what is it.

2024-07-05 20:21 UTC, kchibisov requested changes
Also need a CHANGELOG entry.

2024-07-10 14:45 UTC, madsmtm commented on src/unix.rs
> +    pub connector_id: Option<NonZeroU32>,
Also ideally with links to other documentation explaining it, if such docs exist.

2024-07-10 14:45 UTC, madsmtm commented on src/unix.rs
>      /// let handle = DrmWindowHandle::new(plane);
Please update this example to also set the `connector_id`

2024-07-11 18:44 UTC, kchibisov approved these changes
From my side it's good. Docs are indirectly linked via the description of the struct itself since it's all on the DRM docs, as well as plane stuff.

2024-07-15 15:47 UTC, madsmtm commented on src/unix.rs
>      /// let handle = DrmWindowHandle::new(plane);
What I mean here is something like:

```suggestion
    /// # connector_id = unsafe { NonZeroU32::new_unchecked(1) };
    /// let mut handle = DrmWindowHandle::new(plane);
    /// handle.connector_id = Some(connector_id);
```

2024-07-15 15:53 UTC, morr0ne commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
Using the _with_* suffix aligns with better with rust's coding guidelines, promoting more idiomatic code. If there is a consensus that this requires further discussion, I can amend the changes and open a separate pr. However, I believe this approach is the most appropriate for exposing the api and that similar constructors should be considered for other platforms as well.

Implementing these constructors will not compromise backwards compatibility, as the only scenario requiring their removal would be the elimination of the corresponding fields. In such a case, a breaking change would be inevitable regardless.

2024-07-15 16:00 UTC, morr0ne commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
Furthermore, implementing a separate constructor prevents unnecessary mutability of the created handle, which typically does not require any kind of modification.

2024-07-15 17:50 UTC, kchibisov commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
I'm generally against constructors like that in this crate because they are prone to factorial growth. So if you want to add one more optional field you'd need to add permutations, since you don't generally require all the things to be present.

Unless you just stuck constructors with `Option` but I don't see a point in it given that you can just build with `WindowHandle { }` syntax because it's a `pod` with all fields being `pub`.

I'm also not that much in love with `::new` methods, but it's more of a shorthand for essential stuff, I guess.

2024-07-15 18:01 UTC, morr0ne commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
The primary justification for introducing a new constructor is that it is not feasible to manually instantiate a handle due to the struct being marked as non_exhaustive. This is not merely a matter of convenience or shorthand. Structs marked as non_exhaustive cannot be instantiated outside of their originating crate. A dedicated function to construct one is mandatory.

2024-07-15 18:20 UTC, kchibisov commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
They can as long as they have `Default` but I forgot that we don't have it because we can not really provide `Default`. I still don't like the constructor because factorial growth.

2024-07-15 18:26 UTC, morr0ne commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
> They can as long as they have `Default` but I forgot that we don't have it because we can not really provide `Default`. I still don't like the constructor because factorial growth.

The proper solution would be to only have one constructor that takes all the parameters but that would break backwards compatibility and require a version bump. My understanding was that we should avoid that if possible.

2024-07-15 18:34 UTC, kchibisov commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
The connector is optional though, since not all APIs require it and some APIs may require a list of connectors.

2024-07-15 18:37 UTC, morr0ne commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
> The connector is optional though, since not all APIs require it and some APIs may require a list of connectors.

Which perfectly translates into the new constructor. A new constructor like this would only be necessary for an optional field.

I am also not aware of any API that requires a least of connectors that would also consume a window handle. Do you have any examples? If that's the case then maybe the signature of field should be reconsidered. My main use case for this is implementing a drm backend for wgpu which afaik would require only a specific connector, at least for the vulkan backend.

2024-07-16 14:04 UTC, madsmtm commented on src/unix.rs
> +    pub fn new_with_connector_id(plane: u32, connector_id: NonZeroU32) -> Self {
I'd like @Lokathor's opinion - but as stated in my first comment, this is very much a nit

2024-08-10 00:30 UTC, morr0ne commented
Could you please provide an update on the possibility of merging this PR?

2024-08-10 00:33 UTC, Lokathor commented
Ah, sorry this one slipped out of my attention.

I will double check later but in general we probably want as many optional fields to be supported as possible so this is likely to be approved.

2024-08-10 22:47 UTC, morr0ne commented
Based on the discussion in [this comment](https://github.com/gfx-rs/wgpu/pull/5908#issuecomment-2282298497), I am reconsidering whether this patch is the most effective approach to achieve my final objective. I'm currently unsure how to mark the pull request as not ready for merging on my end, but for now, it should be treated as such.

2024-08-10 22:47 UTC, MarijnS95 commented
> To provide additional context, this change is necessary for adding support to wgpu. Specifically, Vulkan requires a connector_id when creating the surface. You can see how this is used here: https://github.com/gfx-rs/wgpu/pull/5908

To relay some of my comment over at that WGPU PR, Vulkan doesn't specifically require the connector ID especially because `VK_KHR_display` is DRM-agnostic. There just happen to be a few more Vulkan extensions that make it slightly easier to get/identify a `VkDisplayKHR` instance given a connector ID, but it depends on the driver if that's even supported (and the Vulkan API has other, DRM-agnostic means to query `VkDisplayKHR`s, so I would in general be careful when tying the two concepts together).

Because the way you plan to use this now seems to rely on the _receiver of the `DrmWindowHandle`_ doing the modeset (this is what `VK_KHR_display` has to do internally on DRM platforms), the caller also has to _somehow_ specify which mode and pipe/plane to use. Is this something that should be captured in `DrmWindowHandle` as well?
Unfortunately the `VK_EXT_acquire_drm_display` extension used to map a connector ID to a `VkDisplayKHR` doesn't also provide a way to map a DRM CRTC/plane to its Vulkan representation (if the driver didn't abstract this concept away in the first place).

---

As a side-note, regardless of how we continue, let's replace `DrmDisplayHandle` with `DrmWindowHandle` in the title :)

2024-08-11 01:15 UTC, Lokathor commented
@morr0ne there's some sort of "draft" status a PR can be set to, but that's not necessary, we can just hold off on a merge until you're confident about the direction of things

2025-03-07 13:09 UTC, morr0ne commented
No longer necessary since https://github.com/gfx-rs/wgpu/pull/7212 got merged

2025-03-07 13:09 UTC, closed without merging