Finish 0.4 update
rust-windowing/raw-window-handle pull request #70
Opened 2021-06-02 22:04 UTC by Friz64

This PR picks up where #67 left off, cleans up the documentation and implements all remaining TODOs and concerns.

---

* Closes #58
* Closes #60
* Closes #63
* Closes #67
* Closes #69

2021-06-02 22:44 UTC, Lokathor commented
I will have a close look at this the next time i have some time for Rust

2021-06-03 01:26 UTC, madsmtm requested changes
This looks nice, but I think you should keep the commit history from https://github.com/rust-windowing/raw-window-handle/pull/67 - maybe merge that first, and rebase this on top

2021-06-03 01:26 UTC, madsmtm commented on src/windows.rs
>  pub struct WindowsHandle {
Let's rename this to `Win32Handle`, now that `WinRTHandle` also exist

2021-06-03 01:26 UTC, madsmtm commented on src/lib.rs
>      Windows(windows::WindowsHandle),
Maybe rename this to `Win32`?

2021-06-03 01:26 UTC, madsmtm commented on src/lib.rs
>  pub mod windows;
Maybe just `pub use` the types directly, so that we can change the module structure in the future if we desire

2021-06-03 01:26 UTC, madsmtm commented on src/android.rs
>  pub struct AndroidHandle {
Maybe rename this to `AndroidNDKHandle` or similar, to be forwards compatible in case a new Android windowing library appears

2021-06-03 01:26 UTC, madsmtm commented on src/lib.rs
>      Android(android::AndroidHandle),
Maybe rename this to `AndroidNDK` or similar

2021-06-03 01:50 UTC, Friz64 commented on src/windows.rs
>  pub struct WindowsHandle {
Thought about this but initially decided against it because of backwards compatibility. But reconsidering this, i have to agree that if we're doing breaking changes let's get them all out at once. Looking for more opinions.

2021-06-03 01:50 UTC, Friz64 commented on src/lib.rs
>  pub mod windows;
Does this include switching the underlying modules' visibility to private?

2021-06-03 01:50 UTC, Friz64 commented on src/android.rs
>  pub struct AndroidHandle {
Good thoughts. Can this idea of naming not after the platform but after the windowing system be applied to the remaining handles in this crate? So renaming `RedoxHandle`->`RedoxOrbitalHandle`. What about `WebHandle`?

2021-06-03 01:52 UTC, Friz64 commented
> but I think you should keep the commit history from #67 - maybe merge that first, and rebase this on top

Open to doing this if desired.

2021-06-03 02:09 UTC, madsmtm commented on src/lib.rs
>  pub mod windows;
Yeah, I was thinking:
```rust
mod web;
pub use web::WebHandle;
```

Now that we don't have the `cfg`s, doing `raw_window_handle::web::WebHandle` just seems like an unnecessary indirection.

2021-06-03 02:10 UTC, madsmtm commented on src/android.rs
>  pub struct AndroidHandle {
Agree with `RedoxOrbitalHandle` (maybe just `OrbitalHandle`, the other seems a bit long?), but I can't come up with something better for the web.

2021-06-04 23:45 UTC, Lokathor commented
I normally don't place a strong value on git history stuff, as long as the code that's published is correct that's good enough for me.

However, if you know how to merge the history (or whatever you call it) and it's easy enough to do, then it seems like a good idea, since it was asked for.

2021-06-04 23:46 UTC, Lokathor commented
or, if you need me to _actually_ merge #67 to make it work then i can do that.

2021-06-05 01:49 UTC, Friz64 commented
> or, if you need me to actually merge #67 to make it work then i can do that.

Yes, i think we should do that and i'll rebase this as suggested.

2021-06-05 01:54 UTC, Lokathor commented
alright, you're set.

2021-06-05 02:14 UTC, Friz64 commented on src/android.rs
>  pub struct AndroidHandle {
I went with `OrbitalHandle`. As for `WebHandle`: I think it's fine like that.

2021-06-05 08:05 UTC, madsmtm approved these changes
Have a few minor nits, but doesn't matter much, approved from my side

2021-06-05 08:05 UTC, madsmtm commented on src/redox.rs
> +        OrbitalHandle {
Nit: use `Self`:
```suggestion
    pub fn empty() -> Self {
        Self {
```

2021-06-05 08:05 UTC, madsmtm commented on src/lib.rs
> +    UIKit(uikit::UIKitHandle),
Nit:
```suggestion
    UIKit(UIKitHandle),
```

2021-06-05 13:49 UTC, Friz64 commented
I also pushed a commit which moves the "Safety guarantees" documentation to the crate root, making it more prominent. In the previous location, it was easy to miss it.

2021-06-05 14:25 UTC, Lokathor commented
Hmm, but when viewing in rustdoc you usually look at the page for the item itself. In this case the page for the trait. Myself, I rarely look at module level documentation to find out info on a specific item. Also, the rust-analyzer tooltip shows the item's docs not the docs of the module the item goes in.

We could have a message in both places, but i think the trait should have the full safety message and the module should have a note to please see the docs of the trait for the rules.

2021-06-05 15:01 UTC, Friz64 commented
> We could have a message in both places, but i think the trait should have the full safety message and the module should have a note to please see the docs of the trait for the rules.

This is the best solution, thanks!

2021-06-05 15:14 UTC, i509VCB commented
I'm guessing `from_has_raw_window_handle` exists over just implementing `From<H: HasRawWindowHandle>` to make trustng a window handle more explicit?

2021-06-05 15:20 UTC, Lokathor commented
Yeah, because there's unsafe stuff going on we didn't want to just use a standard conversion trait. You should have to pay just a little more attention about what's happening.

2021-06-05 15:51 UTC, Lokathor commented
If everyone is happy I'll merge this in a few hours.

2021-06-05 15:53 UTC, maroider commented on src/android.rs
> +pub struct AndroidNDKHandle {
```suggestion
pub struct AndroidNdkHandle {
```

2021-06-05 16:15 UTC, maroider commented
I just have a minor issue with naming consistency. There are a couple of types/enum variants which derive their names from some other underlying technology/libraray whose name contains an acronym and is typically written in a stylized way:

- UIKit
   - `RawWindowHandle::UIKit`
   - `UIKitHandle`
- XCB
   - `RawWindowHandle::Xcb`
   - `XcbHandle`
- WinRT
   - `RawWindowHandle::WinRT`
   - `WinRTHandle`
- The Android NDK
   - `RawWindowHandle::AndroidNDK`
   - `AndroidNDKHandle`

Out of these, `RawWindowHandle::Xcb` and `XcbHandle` are outliers, as the name of the type/enum variant doesn't follow the same pattern as the others.

I see three options here, and I'm not entirely happy with any of them.

1. Make everything follow the regular capitalization rules for Rust types, i.e. acronyms only get one capital letter.
   This does admittedly look quite ugly, but `AndroidNDKHandle` is going to look ugly to me no matter which way it's written.
2. Use `RawWindowHandle::XCB`, `XCBHandle`
3. Don't do anything. Keep everything as-is.
   I sometimes get hung up on the most inconsequential of details, and this isn't *that* important in the end.

2021-06-05 16:36 UTC, Friz64 commented
I am in favor of option 1. While none of these are perfect, option 1 is the most correct

2021-06-05 16:57 UTC, madsmtm commented
I agree with @Friz64.

So it would be `UiKit[Handle]`, `Xcb[Handle]`, `WinRt[Handle]` and `AndroidNdk[Handle]`, right?

2021-06-05 16:59 UTC, Lokathor commented
I have no strong opinion here, (1) seems reasonable enough.

2021-06-05 17:29 UTC, Friz64 commented
> So it would be `UiKit[Handle]`, `Xcb[Handle]`, `WinRt[Handle]` and `AndroidNdk[Handle]`, right?

Yes exactly.

And regarding the changelog: Is it complete now?

2021-06-05 17:34 UTC, Lokathor commented
Yes, I believe we're all set. I'll merge later if no one speaks up.

2021-06-05 18:01 UTC, i509VCB commented
So a lifetime question regarding the trusted handle. Per the documentation the `TrustedWindowHandle` says you assert the handle is trusted when you insert it into the struct.

The idea of `trusted` is very vague, I'd guess trusted means you refer to all required capabilities to refer to a window completely.

The trusted handle is not Cloneable, so we can rely on that living as long as the scope it was initialized for. However I don't think this garuntees the backing resources of the handle will live longer than the handle itself.

I may consider what vulkano does with their surface object, which also takes a window object, be it a winit window or an Arc to act as a sort of anchor for making the trusted handle live long enough.

2021-06-05 18:25 UTC, madsmtm commented
Yeah, you do have a point - Maybe the API should be completely changed to something like:
```rust
pub trait HasTrustedWindowHandle {
    fn trusted_window_handle<'a>(&'a self) -> TrustedWindowHandle<'a>;
}

#[derive(...)]
pub struct TrustedWindowHandle<'a> {
    raw: RawWindowHandle,
    _phantom: PhantomData<&'a ()>,
}

impl<'a> TrustedWindowHandle<'a> {
    pub const unsafe fn from_raw(raw: RawWindowHandle) -> Self { ... }
    pub fn as_raw(&self) -> RawWindowHandle { ... }
}

impl From<TrustedWindowHandle<'a>> for RawWindowHandle { ... }
```

`TrustedWindowHandle` would now be the main way to interact with this library.

(Actually, we could rename `TrustedWindowHandle -> WindowHandle` here).

But this still leaves open what `TrustedWindowHandle` really guarantees: For example, is the window guaranteed to be able to be interacted with by calling OS apis? And is this even possible to guarantee this for all platforms (e.g. when closing the window, is it still valid to render into?).

2021-06-05 18:28 UTC, Lokathor commented
The trusted part is supposed to be indicating that the pointers contained, if non-null, are valid (at least when you make the value).

2021-06-05 18:35 UTC, madsmtm commented
But I don't think that is a strong enough guarantee to help e.g. [`gfx::hal::Instance::create_surface`](https://docs.rs/gfx-hal/0.8.0/gfx_hal/trait.Instance.html#tymethod.create_surface) become safe?

2021-06-05 18:39 UTC, Lokathor commented
they just say the handle has to be valid i their safety rules.

if there are other undocumented requirements than that should be documented.

2021-06-05 19:03 UTC, madsmtm commented
Well, not an expert, but I think they actually have the requirement that the window may not be deallocated - for example, on MacOS, dropping `winit::Window` results in closing it and it being deallocated (after AppKit has processed the event). So now, a previously valid `TrustedWindowHandle` would become invalid.

So the following example would cause undefined behaviour, because things created from the `TrustedWindowHandle` was allowed to live longer than the data:
```rust
let window: winit::Window = ...;
let handle = TrustedWindowHandle::from_has_raw_window_handle(&window);
// Changed to take the current TrustedWindowHandle, which would make it "safe"
let surface = backend::Instance::create_surface(handle)?;
drop(window);
// Use `surface` later on, causes undefined behaviour because the window was deallocated.
```

2021-06-05 19:11 UTC, Lokathor commented
So my position on this sort of thing has usually been that you can have an unsafe constructor and then part of the unsafe promise is that you won't use the value (or things based on it in this case) for "too long". So if `from_has_...` is an unsafe call, then i think we could justify the rest of things.

Because the alternative is that we can never ever claim safe surface creation, when we know that the creation step itself isn't causing issues.

probably the surface and window should be bundled together by some code that knows how to make the surface bot outlive the window.

2021-06-05 19:27 UTC, maroider commented
> probably the surface and window should be bundled together by some code that knows how to make the surface bot outlive the window.

I've been meaning to bring this up, but the gfx-rs folks have been thinking about this as well in gfx-rs/wgpu#1463. As I understand it, the thing that's most interesting to guarantee is that the handles you get *stay* valid after you've got a hold of them.

In gfx-rs/wgpu#1463, it was suggested that things (in this case: `wgpu::Surface`) which need a window (`T: HasRawWindowHandle`) should take it by value, provide methods to get the window back as a reference or by value, and that `raw-window-handle` should add the following implementations for `HasRawWindowHandle`:
```rust
impl<'a, T: HasRawWindowHandle> HasRawWindowHandle for &'a T { /* .. */ }
impl<T: HasRawWindowHandle> HasRawWindowHandle for Rc<T> { /* .. */ }
impl<T: HasRawWindowHandle> HasRawWindowHandle for Arc<T> { /* .. */ }
```

With this in mind, I don't see where `TrustedWindowHandle` would fit in.

2021-06-05 19:30 UTC, madsmtm commented
> So if `from_has_...` is an unsafe call, then i think we could justify the rest of things.

It would, but that defeats the bigger purpose of `TrustedWindowHandle`, which is to allow user code to be completely safe.

> probably the surface and window should be bundled together by some code that knows how to make the surface bot outlive the window.

This would be possible on MacOS at least (by `retain`ing the `NSWindow`), don't know about the other platforms, but it would still be unsound without a lifetime parameter on `TrustedWindowHandle`:
```rust
let window: winit::Window = ...;
let handle = TrustedWindowHandle::from_has_raw_window_handle(&window);
drop(window);

// Later on when the window has been deallocated:
let surface = backend::Instance::create_surface(handle)?;
```

2021-06-05 19:39 UTC, madsmtm commented
> In https://github.com/gfx-rs/wgpu/issues/1463, it was suggested that things (in this case: `wgpu::Surface`) which need a window (`T: HasRawWindowHandle`) should take it by value

Thanks for the reference! This is definitely a path forward, though I think it's pretty unergonomic that the user would no longer have full control over the window.

But then again, it might be unsafe if they did, or if the surface didn't somehow take mutable ownership (e.g. attempting to create two surfaces on the same window would need to be guarded against, since it would very likely cause undefined behaviour).

2021-06-05 19:50 UTC, Lokathor commented
> it would still be unsound without a lifetime parameter on TrustedWindowHandle

Kinda, you'd have to not have a surface and window separate, they'd have to be combined so that you can't drop them in the wrong order. Then the end user code would only handle the bundle and not interact with the inner fields directly.

to tell you the truth I don't remember why TrustedWindowHandle was developed, because it's not really needed for end users to have all safe code.

2021-06-05 21:54 UTC, msiglreith commented
Would it be an option to keep the `Option<NonNull<_>>` variant for Android at least? Tbh not sure atm how to resolve this.
Context: https://github.com/rust-windowing/winit/pull/1624#issuecomment-673097014

2021-06-05 22:24 UTC, Lokathor commented
@msiglreith I'm not sure I fully understand the problem. The `winit` folks just _don't want_ to return a null pointer when a handle isn't available? Because that is definitely what should happen.

And we took out all the `Option<NonNull<c_void>>` stuff because Rust makes it a royal pain in the butt to manually be converting between ONN and a pointer all the time.

2021-06-05 23:08 UTC, msiglreith commented
yeah.. well I guess I'm fine with it as I can workaround that part

2021-06-05 23:12 UTC, Lokathor commented
We could maybe make the docs more clear about the expectations, and then you could use that as the basis for a PR to winit to just return the darn null pointer, if that would help you.

2021-06-07 08:31 UTC, DJMcNab commented
I want `TrustedWindowHandle` for `bevy_window` to ensure that it is not locked to a specific windowing library (to make using e.g. rust-sdl2 easier/a drop in replacement)

In this case, it would be the job of `bevy_winit` to remove the `TrustedWindowHandle` component (or even the entire window 👀) before it drops the winit window.

If the conversation here is correct, it seems that completely decoupling these is going to be difficult, and need some more thinking.

I think the most viable choice is `BevyWindow(Arc<dyn HasRawWindowHandle>)` with an unsafe constructor guaranteeing it's possible to create a swapchain from it.

2021-06-16 04:19 UTC, maroider commented
In any case, I think the decision on the safety around `HasRawWindowHandle` shouldn't block this PR, since this PR doesn't touch `RawWindowHandle`, `TrustedWindowHandle`, or the version number (despite the title).

2021-06-16 04:32 UTC, Lokathor commented
Ah, yes, right.

I'll merge as is and we can discuss further if needed before a release.

2021-06-16 04:32 UTC, merged

2021-06-16 06:12 UTC, maroider commented
> we can discuss further if needed before a release.

To that end, I've opened a separate issue (#71).

2021-06-17 19:33 UTC, pythonesque commented
> I want `TrustedWindowHandle` for `bevy_window` to ensure that it is not locked to a specific windowing library (to make using e.g. rust-sdl2 easier/a drop in replacement)
> 
> In this case, it would be the job of `bevy_winit` to remove the `TrustedWindowHandle` component (or even the entire window 👀) before it drops the winit window.
> 
> If the conversation here is correct, it seems that completely decoupling these is going to be difficult, and need some more thinking.
> 
> I think the most viable choice is `BevyWindow(Arc<dyn HasRawWindowHandle>)` with an unsafe constructor guaranteeing it's possible to create a swapchain from it.

FWIW, if the `HasRawWindowHandle` implementation for `Arc` goes through, I think what you proposed should work without needing anything special.  *However*, due to `Arc::make_mut`, I'm not sure the Arc implementation is actually safe :|  I need to think about this more.

2021-06-25 23:47 UTC, a1phyr commented
>  However, due to `Arc::make_mut`, I'm not sure the Arc implementation is actually safe :|

It is not a issue because `Arc::make_mut` requires `T: Clone` and therefore `T: Sized` which is not the case for `dyn HasRawWindowHandle`

2021-06-25 23:49 UTC, pythonesque commented
> > However, due to `Arc::make_mut`, I'm not sure the Arc implementation is actually safe :|
> 
> It is not a issue because `Arc::make_mut` requires `T: Clone` and therefore `T: Sized` which is not the case for `dyn HasRawWindowHandle`

From what I have heard, this isn't necessarily something that can be relied on going forward to prevent moves, while `Pin` can.

2021-06-26 01:37 UTC, Lokathor commented
Can someone explain the Arc::make_mut concern in more detail? Is the idea that someone could run a mem::swap using the &mut RawWindowHandle to change the value out from under you?