Add GBM handle
rust-windowing/raw-window-handle pull request #91
Opened 2022-05-03 12:25 UTC by StratusFearMe21

See [my PR for winit](https://github.com/rust-windowing/winit/pull/2272)

2022-05-03 16:42 UTC, Lokathor commented
I'm very happy to see this added!

Is it all set to be merged or did you want to do more?

2022-05-03 19:59 UTC, madsmtm requested changes

2022-05-03 19:59 UTC, madsmtm commented on src/unix.rs
> +pub struct DrmHandle {
Missing documentation.

2022-05-03 19:59 UTC, madsmtm commented on src/lib.rs
> +    Drm(DrmHandle),
Maybe place this below the `Wayland` variant?

2022-05-03 20:14 UTC, StratusFearMe21 commented on src/lib.rs
> +    Drm(DrmHandle),
Awesome, done

2022-05-03 20:14 UTC, StratusFearMe21 commented on src/unix.rs
> +pub struct DrmHandle {
Whoops, sorry about that, just fixed it

2022-05-03 20:15 UTC, StratusFearMe21 commented
It is all set to be merged

2022-05-04 06:24 UTC, Lokathor approved these changes

2022-05-04 06:25 UTC, Lokathor commented
I'm happy with this, but I want to give @madsmtm a chance to double check.

2022-05-04 10:48 UTC, madsmtm approved these changes
My blocker was having no docs on `DrmHandle`, with that fixed I'm satisfied

2022-05-04 10:48 UTC, madsmtm commented on src/lib.rs
> +    /// This variant is used on Linux when X nor Wayland are available
Nit: You committed my `neither` suggestion, but I think it got lost in a merge

2022-05-04 13:19 UTC, merged